# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-27 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('Clothes', 'Clothes'), ('Toys', 'Toys'), ('Supplies', 'Supplies')], max_length=100)),
                ('animal', models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog')], max_length=20)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=20)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
